project:
  type: website

website:
  title: "Homo Calculans"
  navbar:
    right:
      - about.qmd
resources:
    - "assets/*"
format:
  html:
    theme:
      - vapor
      - custom.scss
    css: styles.css



