---
title: "Workshop: Madness in Method"
editor: source
bibliography: workshop.bib
---

Computation is more than a tool—it is a way of thinking. Or is it? Join us for a short-day workshop to meet digital researchers across the HASS disciplines, to critique the concepts of ‘digital’ and ‘method’, and to establish a set of principles for the adoption of digital methods. The workshop features provocative keynotes, an interactive data session, lightning talks, structured interaction and will culminate in the collective authorship of 10 Theses on Method.

**Where:** [The Digital Lab](https://maps.unimelb.edu.au/point?identifier=PAR;148B;2;213), Arts West, University of Melbourne

**When:** Wednesday, September the 10th, 10AM-4PM

[Register via Humanitix](https://events.humanitix.com/madness-in-method)

The Digital Lab can be hard to find. Someone will be waiting at the main entrance of Arts West from 9:45 to help you find it. The link above can also generate directions for you.

## Methods and Madness

> [Hamlet]{.smallcaps}\
I am but mad north-north-west: when the wind is\
southerly I know a hawk from a handsaw.

What makes methods 'mad'? In the Humanities and Social Sciences, 'method' has usually been a bulwark of sanity. Methods ensure that objects exist. When scholars use the proper methods, they can ensure that their research is 'objective', a key epistemic virtue in the Humanities since the 1800s [@daston_objectivity_2014]. Methods achieve objectivity in the same way recipes achieve dishes. A good recipe always cooks the same cake, no matter the cook. Since the cake doesn't depend on the cook, we can agree that the cake is an independent object, that does not rely on the intervention of a particular human subject. Like recipes, research methods guarantee the independence of the objects of research. Some Humanists and Social Scientists have embraced methodical objectivity, especially as computation has enabled more complex and sophisticated methods in all branches of research. Others have rejected methodical objectivity as an improper encroachment of positivism into humanistic learning.

This workshop offers a third approach, inspired by the 'counter-methods' of Paul @feyerabend_against_1975, the 'assemblage methods' of John @law_after_2004, the 'pataphysical' methods of Stephen @ramsay_reading_2011, the 'interface methods' of Noortje Marres and Carolin Geerlitz [-@marres_interface_2016], and the creative works of algorithmic artists from Laurie Spiegel to Refik Anadol. Sure, methods might create objects—but do they always have to create the same, sane ones? How might digital methods help us to reimagine, reshape or recreate the world?

## Programme

### 10:00 | Welcome to the Past

[Michael Falk](https://michaelfalk.io) and Niles Zhao introduce the project, and provide an historical overview of digital methods in the Humanities and Social Sciences, using the project corpus.

### 10:45 | Meet the Method

'Speed dating' activity, to discover the mad methods of other workshop attendees. Structured. Fun. Totally professional.

| Round | Discussion Prompt |
|-------|----------------------|
| 1 | What makes a method ‘digital’? Are there any methods you aren’t sure about? |
| 2 | Does the qualitative/quantitative distinction apply to digital methods in your work or discipline? Why or why not? |
| 3 | What is the biggest impact digital methods have had on your respective disciplines? |
| 4 | Are Digital Humanities/Social Sciences necessarily positivist or empirical? If so, or if not, is this a problem? |
| 5 | Is it necessary to be interdisciplinary to use digital methods? |
| 6 | What are the ethical implications of using digital methods today? |

If you don't use specific 'digital methods' in your work, you can think about the digital mediation of your (non)-digital methods. For example, using databases for literature search or to view archival materials.

### 11:30 | Method and Materiality

[Kath Bode](https://researchportalplus.anu.edu.au/en/persons/katherine-bode) (ANU) presents her critical study of the materiality of digital methods.

Kath is Professor of Literary and Textual Studies at the Australian National University. She is the author of two pathbreaking books in Computational Literary Studies: [*Reading By Numbers*](https://anthempress.com/books/reading-by-numbers-pb) (2012) and [*A World of Fiction: Digital Collections and the Future of Literary History*](https://press.umich.edu/Books/A/A-World-of-Fiction) (2018). Kath has made her name as a powerful critic of so-called "distant reading," but unlike other critics of this trend in scholarship, Kath has launched her critique from within digital humanities. She proposes a unique approach the digital text, rooted in the classic techniques of textual scholarship. In this talk, Kath will give us a sneak peek of her next book, provisionally entitled *Computing Literature*, which draws on her ARC Future Fellowship, *Reading at the interface: literatures, cultures, technologies*.

### 12:30 | Lunch

*Uncatered, sorry!*

### 01:30 | Lightning Talks

Presenters have 7 minutes + 1 slide to present a digital method, and explain how it has impacted their discipline.

[Philip Pond](https://findanexpert.unimelb.edu.au/profile/858659-philip-pond) (Media Studies / Non-time Series)

[Jasmin Pfefferkorn](https://jasminpfefferkorn.com/about) (Museum Studies / Digital Walkthrough)

[Finn Morgan](https://www.fiannualamorgan.com/cv) (Literary Studies / Heuristics)

[Mitch Goodwin](https://lobster-celery-ghdj.squarespace.com/home) (Art / Style Parameters)

[Nat Cutter](https://natcutter.com/) (History / LLMs)

### 02:30 | Mapping as Method

[Luca Scholz](https://lucascholz.com/) (Manchester) presents his work in the history of spatial humanities.

Luca is a historian and digital humanist, and is Senior Lecturer in the Centre for Digital Humanities, Culture and Media at the University of Manchester. He specialises in the spatial humanities. He is at once an expert in the history of mapping, and in the application of new kinds of digital mapping to history. He is the author of [*Borders and Freedom of Movement in the Holy Roman Empire*](https://global.oup.com/academic/product/borders-and-freedom-of-movement-in-the-holy-roman-empire-9780198845676?cc=it&lang=en), published with OUP in 2020, and is currently working on his second book, a digital history of the amusing European practice of "weather-shooting." Using the techniques of spatial humanities, Luca is mapping the spread of this bizarre and endearing practice from the 1600s to the 1900s. Today he will talk to us about the kinds of spatial methods he uses, and how they can enlighten the historian.

### 03:30 | Theses on Method

Collective writing and reflection session. Can we distil today's discussion into 5, 10 or 15 [theses on method](https://docs.google.com/document/d/1Mb6UM5pEuAqTtK16S9wx9_rDtihlY3qmx36fMwa-o90/edit?tab=t.0)?

### 04:00 | Goodbye!

## References
